<html>
    <head>
        <title>Profile</title>
    </head>
    <body>
        <?php
            require('Controller/ControllerStable.php');
            CheckSesion();
            CheckCo();
            require('Controller/ControllerProfile.php');
            PrintProfile();
        ?>
    </body>
</html>        